import Head from 'next/head'
import {} from "antd";
import Header from "@/components/header";
import Footer from "@/components/footer";
import PageContent from "@/components/pageContent";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="home">
              <Header />
              <PageContent />
              <Footer />
        </div>
   
    </>
  )
}
